### ISSUE TITLE
Suggestions and Acknowledgements

### ISSUE THREAD

**Issue by zunairkhan811** [codedit334/Portfolio_Microverse#5]
1- It would be good if you add something in alt for images in html and try to enclose image in &lt;a&gt; tags from line 122 to 
    124 as it will be beneficial in giving links to images and the text will appear in case image doesn't appear[Muhammad Zunair 
     khan suggestion].
2- Kindly try to avoid using fix pixel sizes use rem for responsiveness for professional development.[Mbale kagheni Suggestion].
3- Everthing looks ok to me [Alaska Acknowledgement]

**Comment by codedit334** [comment]
Thank you for your observations and suggestions, i updated the code ...
Feel free to check it out.
@zunairkhan811 
@Kaghenimbale
@Stephen-Adom
